-- 코드를 작성해주세요
WITH FIRST_GEN AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS (
    SELECT A.ID
    FROM ECOLI_DATA A
    INNER JOIN FIRST_GEN B
    ON A.PARENT_ID = B.ID
)
SELECT A.ID
FROM ECOLI_DATA A
INNER JOIN SECOND_GEN B
ON A.PARENT_ID = B.ID
ORDER BY A.ID
