-- 코드를 작성해주세요
WITH RECURSIVE GENERATIONS AS (
    -- 1세대: 부모 NULL
    SELECT 
        ID,
        1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 이후 세대
    SELECT
        E.ID,
        G.GEN + 1 AS GEN
    FROM ECOLI_DATA E
    INNER JOIN GENERATIONS G
        ON E.PARENT_ID = G.ID
    WHERE G.GEN < 3
)
SELECT ID
FROM GENERATIONS
WHERE GEN = 3
ORDER BY ID