-- 코드를 작성해주세요
WITH RECURSIVE GENERATIONS AS (
    SELECT ID,
        1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID,
        G.GEN + 1 AS GEN
    FROM ECOLI_DATA E
    INNER JOIN GENERATIONS G
    ON E.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT, G.GEN AS GENERATION
FROM ECOLI_DATA E
INNER JOIN GENERATIONS G
ON E.ID = G.ID
WHERE E.ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)
GROUP BY G.GEN
ORDER BY G.GEN