-- 코드를 작성해주세요
SELECT DISTINCT B.ID AS ID, B.GENOTYPE AS GENOTYPE, A.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A
INNER JOIN ECOLI_DATA B
ON (A.ID = B.PARENT_ID
   AND B.GENOTYPE & A.GENOTYPE = A.GENOTYPE
   )
ORDER BY B.ID