-- 코드를 입력하세요
WITH MONTHLY_RECORDS AS (
    SELECT MONTH(START_DATE) AS MONTH,
        CAR_ID, 
        COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m')
)
SELECT MONTH,
    CAR_ID,
    RECORDS
FROM MONTHLY_RECORDS
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM MONTHLY_RECORDS
    GROUP BY CAR_ID
    HAVING SUM(RECORDS) >= 5
)
ORDER BY MONTH, CAR_ID DESC


