-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS DEV
INNER JOIN SKILLCODES SKILL
ON (DEV.SKILL_CODE & SKILL.CODE = SKILL.CODE)
WHERE SKILL.NAME = 'Python'
OR SKILL.NAME = 'C#'
ORDER BY DEV.ID