-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, (A.SIZE_OF_COLONY - E.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E
INNER JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) A
ON YEAR(E.DIFFERENTIATION_DATE) = A.YEAR
ORDER BY YEAR, YEAR_DEV